// <auto-generated />
using System;
using System.Text.Json;
using LogistiqueLesLions.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LogistiqueLesLions.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("vehicles")
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LogistiqueLesLions.Domain.Entities.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uuid")
                        .HasColumnName("buyer_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<bool>("IsArchivedByBuyer")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived_by_buyer");

                    b.Property<bool>("IsArchivedBySeller")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived_by_seller");

                    b.Property<DateTimeOffset?>("LastMessageAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_message_at");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid")
                        .HasColumnName("seller_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id")
                        .HasName("pk_conversations");

                    b.HasIndex("SellerId")
                        .HasDatabaseName("ix_conversations_seller_id");

                    b.HasIndex("VehicleId")
                        .HasDatabaseName("ix_conversations_vehicle_id");

                    b.HasIndex("BuyerId", "SellerId", "VehicleId")
                        .IsUnique()
                        .HasDatabaseName("ix_conversations_buyer_id_seller_id_vehicle_id");

                    b.ToTable("conversations", "messaging");
                });

            modelBuilder.Entity("LogistiqueLesLions.Domain.Entities.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("EUR")
                        .HasColumnName("currency");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("FlagEmoji")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("flag_emoji");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsEuMember")
                        .HasColumnType("boolean")
                        .HasColumnName("is_eu_member");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name_en");

                    b.Property<string>("NameEs")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name_es");

                    b.Property<bool>("SupportsExport")
                        .HasColumnType("boolean")
                        .HasColumnName("supports_export");

                    b.Property<bool>("SupportsImport")
                        .HasColumnType("boolean")
                        .HasColumnName("supports_import");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_countries");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_countries_code");

                    b.ToTable("countries", "vehicles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Code = "ES",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 10, 6, 54, 39, 356, DateTimeKind.Unspecified).AddTicks(9565), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "EUR",
                            DisplayOrder = 1,
                            FlagEmoji = "🇪🇸",
                            IsActive = true,
                            IsEuMember = true,
                            NameEn = "Spain",
                            NameEs = "España",
                            SupportsExport = true,
                            SupportsImport = true,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 4, 10, 6, 54, 39, 356, DateTimeKind.Unspecified).AddTicks(9696), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Code = "DE",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 10, 6, 54, 39, 356, DateTimeKind.Unspecified).AddTicks(9820), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "EUR",
                            DisplayOrder = 2,
                            FlagEmoji = "🇩🇪",
                            IsActive = true,
                            IsEuMember = true,
                            NameEn = "Germany",
                            NameEs = "Alemania",
                            SupportsExport = true,
                            SupportsImport = true,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 4, 10, 6, 54, 39, 356, DateTimeKind.Unspecified).AddTicks(9821), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Code = "FR",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 10, 6, 54, 39, 356, DateTimeKind.Unspecified).AddTicks(9824), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "EUR",
                            DisplayOrder = 3,
                            FlagEmoji = "🇫🇷",
                            IsActive = true,
                            IsEuMember = true,
                            NameEn = "France",
                            NameEs = "Francia",
                            SupportsExport = true,
                            SupportsImport = true,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 4, 10, 6, 54, 39, 356, DateTimeKind.Unspecified).AddTicks(9825), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            Code = "IT",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 10, 6, 54, 39, 356, DateTimeKind.Unspecified).AddTicks(9850), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "EUR",
                            DisplayOrder = 4,
                            FlagEmoji = "🇮🇹",
                            IsActive = true,
                            IsEuMember = true,
                            NameEn = "Italy",
                            NameEs = "Italia",
                            SupportsExport = true,
                            SupportsImport = true,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 4, 10, 6, 54, 39, 356, DateTimeKind.Unspecified).AddTicks(9851), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            Code = "PT",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 10, 6, 54, 39, 356, DateTimeKind.Unspecified).AddTicks(9853), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "EUR",
                            DisplayOrder = 5,
                            FlagEmoji = "🇵🇹",
                            IsActive = true,
                            IsEuMember = true,
                            NameEn = "Portugal",
                            NameEs = "Portugal",
                            SupportsExport = true,
                            SupportsImport = true,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 4, 10, 6, 54, 39, 356, DateTimeKind.Unspecified).AddTicks(9854), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000006"),
                            Code = "NL",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 10, 6, 54, 39, 356, DateTimeKind.Unspecified).AddTicks(9868), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "EUR",
                            DisplayOrder = 6,
                            FlagEmoji = "🇳🇱",
                            IsActive = true,
                            IsEuMember = true,
                            NameEn = "Netherlands",
                            NameEs = "Países Bajos",
                            SupportsExport = true,
                            SupportsImport = true,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 4, 10, 6, 54, 39, 356, DateTimeKind.Unspecified).AddTicks(9868), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000007"),
                            Code = "BE",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 10, 6, 54, 39, 356, DateTimeKind.Unspecified).AddTicks(9871), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "EUR",
                            DisplayOrder = 7,
                            FlagEmoji = "🇧🇪",
                            IsActive = true,
                            IsEuMember = true,
                            NameEn = "Belgium",
                            NameEs = "Bélgica",
                            SupportsExport = true,
                            SupportsImport = true,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 4, 10, 6, 54, 39, 356, DateTimeKind.Unspecified).AddTicks(9871), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000008"),
                            Code = "GB",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 10, 6, 54, 39, 356, DateTimeKind.Unspecified).AddTicks(9884), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "GBP",
                            DisplayOrder = 8,
                            FlagEmoji = "🇬🇧",
                            IsActive = true,
                            IsEuMember = false,
                            NameEn = "United Kingdom",
                            NameEs = "Reino Unido",
                            SupportsExport = true,
                            SupportsImport = true,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 4, 10, 6, 54, 39, 356, DateTimeKind.Unspecified).AddTicks(9885), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000009"),
                            Code = "US",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 10, 6, 54, 39, 356, DateTimeKind.Unspecified).AddTicks(9888), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "USD",
                            DisplayOrder = 9,
                            FlagEmoji = "🇺🇸",
                            IsActive = true,
                            IsEuMember = false,
                            NameEn = "United States",
                            NameEs = "Estados Unidos",
                            SupportsExport = false,
                            SupportsImport = true,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 4, 10, 6, 54, 39, 356, DateTimeKind.Unspecified).AddTicks(9888), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000010"),
                            Code = "MA",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 10, 6, 54, 39, 356, DateTimeKind.Unspecified).AddTicks(9891), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "MAD",
                            DisplayOrder = 10,
                            FlagEmoji = "🇲🇦",
                            IsActive = true,
                            IsEuMember = false,
                            NameEn = "Morocco",
                            NameEs = "Marruecos",
                            SupportsExport = true,
                            SupportsImport = false,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 4, 10, 6, 54, 39, 356, DateTimeKind.Unspecified).AddTicks(9891), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000011"),
                            Code = "JP",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 10, 6, 54, 39, 356, DateTimeKind.Unspecified).AddTicks(9894), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "JPY",
                            DisplayOrder = 11,
                            FlagEmoji = "🇯🇵",
                            IsActive = true,
                            IsEuMember = false,
                            NameEn = "Japan",
                            NameEs = "Japón",
                            SupportsExport = false,
                            SupportsImport = true,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 4, 10, 6, 54, 39, 356, DateTimeKind.Unspecified).AddTicks(9894), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000012"),
                            Code = "CH",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 10, 6, 54, 39, 356, DateTimeKind.Unspecified).AddTicks(9900), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "CHF",
                            DisplayOrder = 12,
                            FlagEmoji = "🇨🇭",
                            IsActive = true,
                            IsEuMember = false,
                            NameEn = "Switzerland",
                            NameEs = "Suiza",
                            SupportsExport = true,
                            SupportsImport = true,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 4, 10, 6, 54, 39, 356, DateTimeKind.Unspecified).AddTicks(9900), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("LogistiqueLesLions.Domain.Entities.CountryRequirement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<decimal>("CustomsRatePercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("customs_rate_percent");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("DestinationCountry")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("destination_country");

                    b.Property<string>("DocumentTypesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("document_types_json");

                    b.Property<int>("EstimatedDays")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_days");

                    b.Property<decimal>("EstimatedProcessingCostEur")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("estimated_processing_cost_eur");

                    b.Property<bool>("HomologationRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("homologation_required");

                    b.Property<DateTimeOffset>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at");

                    b.Property<string>("NotesEn")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes_en");

                    b.Property<string>("NotesEs")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes_es");

                    b.Property<string>("OriginCountry")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("origin_country");

                    b.Property<JsonDocument>("RoadTaxFormula")
                        .HasColumnType("jsonb")
                        .HasColumnName("road_tax_formula");

                    b.Property<bool>("TechnicalInspectionRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("technical_inspection_required");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<decimal>("VatRatePercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("vat_rate_percent");

                    b.HasKey("Id")
                        .HasName("pk_country_requirements");

                    b.HasIndex("OriginCountry", "DestinationCountry")
                        .IsUnique()
                        .HasDatabaseName("ix_country_requirements_origin_country_destination_country");

                    b.ToTable("country_requirements", "compliance");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CustomsRatePercent = 0m,
                            DestinationCountry = "DE",
                            DocumentTypesJson = "[\"FichaTecnica\",\"COC\",\"TituloPropiedad\",\"Itv\"]",
                            EstimatedDays = 15,
                            EstimatedProcessingCostEur = 300m,
                            HomologationRequired = false,
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            NotesEs = "Transferencia intra-UE. Sin aranceles. COC europeo requerido.",
                            OriginCountry = "ES",
                            TechnicalInspectionRequired = false,
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            VatRatePercent = 0m
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CustomsRatePercent = 0m,
                            DestinationCountry = "ES",
                            DocumentTypesJson = "[\"FichaTecnica\",\"COC\",\"TituloPropiedad\"]",
                            EstimatedDays = 10,
                            EstimatedProcessingCostEur = 280m,
                            HomologationRequired = false,
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            NotesEs = "Transferencia intra-UE. ITV en España obligatoria al matricular.",
                            OriginCountry = "DE",
                            TechnicalInspectionRequired = false,
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            VatRatePercent = 0m
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CustomsRatePercent = 0m,
                            DestinationCountry = "FR",
                            DocumentTypesJson = "[\"FichaTecnica\",\"COC\",\"TituloPropiedad\"]",
                            EstimatedDays = 10,
                            EstimatedProcessingCostEur = 250m,
                            HomologationRequired = false,
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            NotesEs = "Transferencia intra-UE Francia. Control técnico (CT) requerido al matricular.",
                            OriginCountry = "DE",
                            TechnicalInspectionRequired = false,
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            VatRatePercent = 0m
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CustomsRatePercent = 6.5m,
                            DestinationCountry = "ES",
                            DocumentTypesJson = "[\"TituloPropiedad\",\"DeclaracionAduana\",\"PagoAranceles\",\"Homologacion\",\"Itv\",\"SeguroImportacion\"]",
                            EstimatedDays = 45,
                            EstimatedProcessingCostEur = 1500m,
                            HomologationRequired = true,
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            NotesEs = "Arancel UE 6.5% sobre valor CIF. IVA 21% sobre valor + arancel. Homologación obligatoria para vehículos no certificados ECE.",
                            OriginCountry = "US",
                            TechnicalInspectionRequired = true,
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            VatRatePercent = 21m
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CustomsRatePercent = 6.5m,
                            DestinationCountry = "ES",
                            DocumentTypesJson = "[\"TituloPropiedad\",\"DeclaracionAduana\",\"PagoAranceles\",\"Homologacion\",\"Itv\",\"SeguroImportacion\"]",
                            EstimatedDays = 60,
                            EstimatedProcessingCostEur = 2000m,
                            HomologationRequired = true,
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            NotesEs = "Importación desde Japón. Requiere homologación y adaptación de luces/faros al estándar europeo.",
                            OriginCountry = "JP",
                            TechnicalInspectionRequired = true,
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            VatRatePercent = 21m
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CustomsRatePercent = 2.5m,
                            DestinationCountry = "MA",
                            DocumentTypesJson = "[\"TituloPropiedad\",\"FichaTecnica\",\"DeclaracionAduana\",\"SeguroImportacion\",\"InspeccionTecnica\"]",
                            EstimatedDays = 30,
                            EstimatedProcessingCostEur = 800m,
                            HomologationRequired = true,
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            NotesEs = "Exportación a Marruecos. Requiere vistazos en aduana de Melilla/Ceuta o flete marítimo. Vehículo debe tener menos de 5 años.",
                            OriginCountry = "ES",
                            TechnicalInspectionRequired = true,
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            VatRatePercent = 20m
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000007"),
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CustomsRatePercent = 6.5m,
                            DestinationCountry = "GB",
                            DocumentTypesJson = "[\"TituloPropiedad\",\"FichaTecnica\",\"DeclaracionAduana\",\"MOT\",\"SeguroImportacion\"]",
                            EstimatedDays = 30,
                            EstimatedProcessingCostEur = 1200m,
                            HomologationRequired = true,
                            LastUpdatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            NotesEs = "Post-Brexit: se aplican aranceles UE-UK. Conversión a conducción por la izquierda no obligatoria pero faros deben ajustarse.",
                            OriginCountry = "ES",
                            TechnicalInspectionRequired = true,
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            VatRatePercent = 20m
                        });
                });

            modelBuilder.Entity("LogistiqueLesLions.Domain.Entities.CustomsTariff", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("DestinationCountry")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("destination_country");

                    b.Property<string>("HsCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("hs_code");

                    b.Property<string>("OriginCountry")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("origin_country");

                    b.Property<string>("Source")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("source");

                    b.Property<decimal>("TariffRatePercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("tariff_rate_percent");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTimeOffset?>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_to");

                    b.HasKey("Id")
                        .HasName("pk_customs_tariffs");

                    b.HasIndex("ValidFrom")
                        .HasDatabaseName("ix_customs_tariffs_valid_from");

                    b.HasIndex("OriginCountry", "DestinationCountry", "HsCode")
                        .HasDatabaseName("ix_customs_tariffs_origin_country_destination_country_hs_code");

                    b.ToTable("customs_tariffs", "compliance");
                });

            modelBuilder.Entity("LogistiqueLesLions.Domain.Entities.DocumentTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("country");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("document_type");

                    b.Property<decimal?>("EstimatedCostEur")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("estimated_cost_eur");

                    b.Property<int?>("EstimatedDays")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_days");

                    b.Property<string>("InstructionsEn")
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)")
                        .HasColumnName("instructions_en");

                    b.Property<string>("InstructionsEs")
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)")
                        .HasColumnName("instructions_es");

                    b.Property<string>("IssuingAuthority")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("issuing_authority");

                    b.Property<string>("OfficialUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("official_url");

                    b.Property<string>("TemplateUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("template_url");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_document_templates");

                    b.HasIndex("Country", "DocumentType")
                        .HasDatabaseName("ix_document_templates_country_document_type");

                    b.ToTable("document_templates", "compliance");
                });

            modelBuilder.Entity("LogistiqueLesLions.Domain.Entities.HomologationRequirement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CertifyingBody")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("certifying_body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("DestinationCountry")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("destination_country");

                    b.Property<string>("EmissionStandard")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("emission_standard");

                    b.Property<decimal>("EstimatedCostEur")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("estimated_cost_eur");

                    b.Property<string>("NotesEn")
                        .HasColumnType("text")
                        .HasColumnName("notes_en");

                    b.Property<string>("NotesEs")
                        .HasColumnType("text")
                        .HasColumnName("notes_es");

                    b.Property<JsonDocument>("RequiredModifications")
                        .HasColumnType("jsonb")
                        .HasColumnName("required_modifications");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<string>("VehicleCategory")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("vehicle_category");

                    b.Property<int?>("YearFrom")
                        .HasColumnType("integer")
                        .HasColumnName("year_from");

                    b.Property<int?>("YearTo")
                        .HasColumnType("integer")
                        .HasColumnName("year_to");

                    b.HasKey("Id")
                        .HasName("pk_homologation_requirements");

                    b.HasIndex("DestinationCountry")
                        .HasDatabaseName("ix_homologation_requirements_destination_country");

                    b.HasIndex("DestinationCountry", "VehicleCategory")
                        .HasDatabaseName("ix_homologation_requirements_destination_country_vehicle_categ");

                    b.ToTable("homologation_requirements", "compliance");
                });

            modelBuilder.Entity("LogistiqueLesLions.Domain.Entities.ImportExportProcess", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("ActualCostEur")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("actual_cost_eur");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uuid")
                        .HasColumnName("buyer_id");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("cancellation_reason");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<int>("CompletionPercent")
                        .HasColumnType("integer")
                        .HasColumnName("completion_percent");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("DestinationCountry")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("destination_country");

                    b.Property<decimal?>("EstimatedCostEur")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("estimated_cost_eur");

                    b.Property<JsonDocument>("Notes")
                        .HasColumnType("jsonb")
                        .HasColumnName("notes");

                    b.Property<string>("OriginCountry")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("origin_country");

                    b.Property<string>("ProcessType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("process_type");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid")
                        .HasColumnName("seller_id");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id")
                        .HasName("pk_import_export_processes");

                    b.HasIndex("BuyerId")
                        .HasDatabaseName("ix_import_export_processes_buyer_id");

                    b.HasIndex("SellerId")
                        .HasDatabaseName("ix_import_export_processes_seller_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_import_export_processes_status");

                    b.HasIndex("VehicleId")
                        .HasDatabaseName("ix_import_export_processes_vehicle_id");

                    b.ToTable("import_export_processes", "compliance");
                });

            modelBuilder.Entity("LogistiqueLesLions.Domain.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("body");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid")
                        .HasColumnName("sender_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_messages");

                    b.HasIndex("ConversationId")
                        .HasDatabaseName("ix_messages_conversation_id");

                    b.HasIndex("SenderId")
                        .HasDatabaseName("ix_messages_sender_id");

                    b.ToTable("messages", "messaging");
                });

            modelBuilder.Entity("LogistiqueLesLions.Domain.Entities.NewsletterSubscriber", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset>("SubscribedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("subscribed_at");

                    b.HasKey("Id")
                        .HasName("pk_newsletter_subscribers");

                    b.ToTable("newsletter_subscribers", "vehicles");
                });

            modelBuilder.Entity("LogistiqueLesLions.Domain.Entities.ProcessDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("country");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("document_type");

                    b.Property<decimal?>("EstimatedCostEur")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("estimated_cost_eur");

                    b.Property<string>("FileUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("file_url");

                    b.Property<string>("InstructionsEs")
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)")
                        .HasColumnName("instructions_es");

                    b.Property<string>("OfficialUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("official_url");

                    b.Property<Guid>("ProcessId")
                        .HasColumnType("uuid")
                        .HasColumnName("process_id");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text")
                        .HasColumnName("rejection_reason");

                    b.Property<DateTimeOffset?>("RequiredByDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("required_by_date");

                    b.Property<string>("ResponsibleParty")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("responsible_party");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("TemplateUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("template_url");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<DateTimeOffset?>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.Property<DateTimeOffset?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.HasKey("Id")
                        .HasName("pk_process_documents");

                    b.HasIndex("ProcessId")
                        .HasDatabaseName("ix_process_documents_process_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_process_documents_status");

                    b.ToTable("process_documents", "compliance");
                });

            modelBuilder.Entity("LogistiqueLesLions.Domain.Entities.SavedVehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id")
                        .HasName("pk_saved_vehicles");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_saved_vehicles_user_id");

                    b.HasIndex("VehicleId")
                        .HasDatabaseName("ix_saved_vehicles_vehicle_id");

                    b.HasIndex("UserId", "VehicleId")
                        .IsUnique()
                        .HasDatabaseName("ix_saved_vehicles_user_id_vehicle_id");

                    b.ToTable("saved_vehicles", "vehicles");
                });

            modelBuilder.Entity("LogistiqueLesLions.Domain.Entities.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("avatar_url");

                    b.Property<string>("Bio")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("bio");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("company_name");

                    b.Property<string>("CompanyVat")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("company_vat");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("country_code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_verified");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("refresh_token");

                    b.Property<DateTimeOffset?>("RefreshTokenExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_token_expires_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_user_profiles");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_user_profiles_email");

                    b.ToTable("user_profiles", "users");
                });

            modelBuilder.Entity("LogistiqueLesLions.Domain.Entities.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BodyType")
                        .HasColumnType("text")
                        .HasColumnName("body_type");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("color");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("condition");

                    b.Property<int>("ContactsCount")
                        .HasColumnType("integer")
                        .HasColumnName("contacts_count");

                    b.Property<string>("CountryOrigin")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("country_origin");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("EUR")
                        .HasColumnName("currency");

                    b.Property<Guid?>("DealerId")
                        .HasColumnType("uuid")
                        .HasColumnName("dealer_id");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("DescriptionEn")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("description_en");

                    b.Property<string>("DescriptionEs")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("description_es");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<int>("FavoritesCount")
                        .HasColumnType("integer")
                        .HasColumnName("favorites_count");

                    b.Property<JsonDocument>("Features")
                        .HasColumnType("jsonb")
                        .HasColumnName("features");

                    b.Property<string>("FuelType")
                        .HasColumnType("text")
                        .HasColumnName("fuel_type");

                    b.Property<bool>("IsExportReady")
                        .HasColumnType("boolean")
                        .HasColumnName("is_export_ready");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean")
                        .HasColumnName("is_featured");

                    b.Property<Guid>("MakeId")
                        .HasColumnType("uuid")
                        .HasColumnName("make_id");

                    b.Property<int?>("Mileage")
                        .HasColumnType("integer")
                        .HasColumnName("mileage");

                    b.Property<Guid?>("ModelId")
                        .HasColumnType("uuid")
                        .HasColumnName("model_id");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("postal_code");

                    b.Property<decimal>("Price")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("price");

                    b.Property<bool>("PriceNegotiable")
                        .HasColumnType("boolean")
                        .HasColumnName("price_negotiable");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid")
                        .HasColumnName("seller_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset?>("SoldAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sold_at");

                    b.Property<JsonDocument>("Specs")
                        .HasColumnType("jsonb")
                        .HasColumnName("specs");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<string>("Transmission")
                        .HasColumnType("text")
                        .HasColumnName("transmission");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<int>("ViewsCount")
                        .HasColumnType("integer")
                        .HasColumnName("views_count");

                    b.Property<string>("Vin")
                        .HasMaxLength(17)
                        .HasColumnType("character varying(17)")
                        .HasColumnName("vin");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_vehicles");

                    b.HasIndex("CountryOrigin")
                        .HasDatabaseName("ix_vehicles_country_origin");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_vehicles_created_at");

                    b.HasIndex("MakeId")
                        .HasDatabaseName("ix_vehicles_make_id");

                    b.HasIndex("ModelId")
                        .HasDatabaseName("ix_vehicles_model_id");

                    b.HasIndex("SellerId")
                        .HasDatabaseName("ix_vehicles_seller_id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_vehicles_slug");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_vehicles_status");

                    b.HasIndex("Price", "Currency")
                        .HasDatabaseName("ix_vehicles_price_currency");

                    b.HasIndex("Status", "IsFeatured", "DeletedAt")
                        .HasDatabaseName("ix_vehicles_active_featured")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("vehicles", "vehicles");
                });

            modelBuilder.Entity("LogistiqueLesLions.Domain.Entities.VehicleDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("country");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("file_url");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.Property<DateTimeOffset?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.Property<Guid?>("VerifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("verified_by");

                    b.HasKey("Id")
                        .HasName("pk_vehicle_documents");

                    b.HasIndex("VehicleId", "Type")
                        .HasDatabaseName("ix_vehicle_documents_vehicle_id_type");

                    b.ToTable("vehicle_documents", "vehicles");
                });

            modelBuilder.Entity("LogistiqueLesLions.Domain.Entities.VehicleHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Country")
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("EventDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("event_date");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("event_type");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_verified");

                    b.Property<int?>("MileageAtEvent")
                        .HasColumnType("integer")
                        .HasColumnName("mileage_at_event");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id")
                        .HasName("pk_vehicle_histories");

                    b.HasIndex("EventDate")
                        .HasDatabaseName("ix_vehicle_histories_event_date");

                    b.HasIndex("VehicleId")
                        .HasDatabaseName("ix_vehicle_histories_vehicle_id");

                    b.ToTable("vehicle_histories", "vehicles");
                });

            modelBuilder.Entity("LogistiqueLesLions.Domain.Entities.VehicleImage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AltText")
                        .HasColumnType("text")
                        .HasColumnName("alt_text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Format")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("webp")
                        .HasColumnName("format");

                    b.Property<int?>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("thumbnail_url");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("url");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.Property<int?>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("pk_vehicle_images");

                    b.HasIndex("VehicleId", "IsPrimary")
                        .HasDatabaseName("ix_vehicle_images_vehicle_id_is_primary");

                    b.HasIndex("VehicleId", "SortOrder")
                        .HasDatabaseName("ix_vehicle_images_vehicle_id_sort_order");

                    b.ToTable("vehicle_images", "vehicles");
                });

            modelBuilder.Entity("LogistiqueLesLions.Domain.Entities.VehicleMake", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Country")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("country");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<bool>("IsPopular")
                        .HasColumnType("boolean")
                        .HasColumnName("is_popular");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("logo_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_vehicle_makes");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_vehicle_makes_name");

                    b.ToTable("vehicle_makes", "vehicles");
                });

            modelBuilder.Entity("LogistiqueLesLions.Domain.Entities.VehicleModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BodyTypes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body_types");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<Guid>("MakeId")
                        .HasColumnType("uuid")
                        .HasColumnName("make_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_vehicle_models");

                    b.HasIndex("MakeId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_vehicle_models_make_id_name");

                    b.ToTable("vehicle_models", "vehicles");
                });

            modelBuilder.Entity("LogistiqueLesLions.Domain.Entities.Conversation", b =>
                {
                    b.HasOne("LogistiqueLesLions.Domain.Entities.UserProfile", "Buyer")
                        .WithMany()
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_conversations_user_profiles_buyer_id");

                    b.HasOne("LogistiqueLesLions.Domain.Entities.UserProfile", "Seller")
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_conversations_user_profiles_seller_id");

                    b.HasOne("LogistiqueLesLions.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_conversations_vehicles_vehicle_id");

                    b.Navigation("Buyer");

                    b.Navigation("Seller");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("LogistiqueLesLions.Domain.Entities.ImportExportProcess", b =>
                {
                    b.HasOne("LogistiqueLesLions.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_import_export_processes_vehicles_vehicle_id");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("LogistiqueLesLions.Domain.Entities.Message", b =>
                {
                    b.HasOne("LogistiqueLesLions.Domain.Entities.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_messages_conversations_conversation_id");

                    b.HasOne("LogistiqueLesLions.Domain.Entities.UserProfile", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_messages_user_profiles_sender_id");

                    b.Navigation("Conversation");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("LogistiqueLesLions.Domain.Entities.ProcessDocument", b =>
                {
                    b.HasOne("LogistiqueLesLions.Domain.Entities.ImportExportProcess", "Process")
                        .WithMany("Documents")
                        .HasForeignKey("ProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_process_documents_import_export_processes_process_id");

                    b.Navigation("Process");
                });

            modelBuilder.Entity("LogistiqueLesLions.Domain.Entities.SavedVehicle", b =>
                {
                    b.HasOne("LogistiqueLesLions.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_saved_vehicles_vehicles_vehicle_id");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("LogistiqueLesLions.Domain.Entities.Vehicle", b =>
                {
                    b.HasOne("LogistiqueLesLions.Domain.Entities.VehicleMake", "Make")
                        .WithMany("Vehicles")
                        .HasForeignKey("MakeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vehicles_vehicle_makes_make_id");

                    b.HasOne("LogistiqueLesLions.Domain.Entities.VehicleModel", "Model")
                        .WithMany("Vehicles")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_vehicles_vehicle_models_model_id");

                    b.HasOne("LogistiqueLesLions.Domain.Entities.UserProfile", "Seller")
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vehicles_user_profiles_seller_id");

                    b.Navigation("Make");

                    b.Navigation("Model");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("LogistiqueLesLions.Domain.Entities.VehicleDocument", b =>
                {
                    b.HasOne("LogistiqueLesLions.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vehicle_documents_vehicles_vehicle_id");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("LogistiqueLesLions.Domain.Entities.VehicleHistory", b =>
                {
                    b.HasOne("LogistiqueLesLions.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vehicle_histories_vehicles_vehicle_id");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("LogistiqueLesLions.Domain.Entities.VehicleImage", b =>
                {
                    b.HasOne("LogistiqueLesLions.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany("Images")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vehicle_images_vehicles_vehicle_id");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("LogistiqueLesLions.Domain.Entities.VehicleModel", b =>
                {
                    b.HasOne("LogistiqueLesLions.Domain.Entities.VehicleMake", "Make")
                        .WithMany("Models")
                        .HasForeignKey("MakeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vehicle_models_vehicle_makes_make_id");

                    b.Navigation("Make");
                });

            modelBuilder.Entity("LogistiqueLesLions.Domain.Entities.Conversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("LogistiqueLesLions.Domain.Entities.ImportExportProcess", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("LogistiqueLesLions.Domain.Entities.Vehicle", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("LogistiqueLesLions.Domain.Entities.VehicleMake", b =>
                {
                    b.Navigation("Models");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("LogistiqueLesLions.Domain.Entities.VehicleModel", b =>
                {
                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
